### ISSUE TITLE
[BUG] Error message for `socialmedia` command is incorrect

### ISSUE THREAD

**Issue by zameschua** [CS2103AUG2017-W10-B1/main#124]
### Description
As a user who's new to the app, the help message is supposed to help me navigate but it ends up being confusing.

### Screenshot
![image](https://user-images.githubusercontent.com/18271085/32362998-fe5b258e-c0a7-11e7-928f-e16b1a6ea1ee.png)

**Comment by kenpaxtonlim** [comment]
Resolved in v1.5
