### ISSUE TITLE
[BUG] Going from `statistics` page to `socialmedia` page does not change the view

### ISSUE THREAD

**Issue by zameschua** [CS2103AUG2017-W10-B1/main#125]
### Description
The view doesn't change after I go from the `statistics` page to the `socialmedia` page.
Seems like a bug that might be present with other commands as well.

### How to re-create
1. Type `statistics` in the command box
2. Access someone's social media page with `socialmedia` command

### Screenshot
![image](https://user-images.githubusercontent.com/18271085/32363135-add2ba5e-c0a8-11e7-8371-669be8d4c5fd.png)

**Comment by 500poundbear** [comment]
@zameschua Thanks, will fix
