### ISSUE TITLE
[NOT SURE IF BUG OR NOT] `birthday` command doesn't work

### ISSUE THREAD

**Issue by zameschua** [CS2103AUG2017-W10-B1/main#129]
### Description
I assumed the birthday command would work since it isn't stated otherwise in the user guide, but it didn't work!!

### Screenshot
![image](https://user-images.githubusercontent.com/18271085/32363584-09bd19ca-c0ab-11e7-8de9-9210879023f8.png)

**Comment by zameschua** [comment]
Hi Ken!

**Comment by kenpaxtonlim** [comment]
Have yet to be implemented, sorry for the confusion!

**Comment by kenpaxtonlim** [comment]
Hi Zames haha
