### ISSUE TITLE
Add sample data XML

### ISSUE THREAD

**Issue by donjar** [CS2103AUG2017-W10-B1/main#152]
{project root}\src\test\data\ManualTesting\[team][Project Name]SampleData.xml : e.g. [T09-B1][ContactsPlus]SampleData.xml Sample data that can be loaded to your app. Should contain 20+ items.

**Comment by 500poundbear** [comment]
@donjar Should be `{project root}\src\test\data\ManualTesting\[team][Project Name]SampleData.xml`

Working on it!

**Comment by 500poundbear** [comment]
done
